### ISSUE TITLE
Already used hooks

### ISSUE THREAD

**Issue by PowerLevel9000** [PowerLevel9000/mathmatica#4]
# I was already using hooks so the explanation

 - [ ] every time when you click on any button event handler is called 
 - [ ] and according to that we have a setResult called on line 11 calculato.js
- [ ] which calculates the result according to the files given by microverse
- [ ] ultimately online 5 set the new state of our calculator each time when we press buttons
- [ ] and operations perform under the hood

## happy coding

![WannaCodeCodeGIF](https://user-images.githubusercontent.com/116451144/220961814-ec6a210c-836a-454c-ace9-51408856f8ec.gif)

**Comment by Danieldotcomcoder** [comment]
Hello @PowerLevel9000 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 

## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

![comp-2](https://user-images.githubusercontent.com/87448628/159119684-e86473c4-9b60-43a3-90f2-54048e841394.gif)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
